import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./_components/ThemeProvider";
import { Roboto } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./_components/AppSidebar";
import AppHeader from "./_components/AppHeader";
import { ClerkProvider } from "@clerk/nextjs";
import { AiModelProvider } from "@/context/AiModelSelectedContext";
import { UserDetailProvider } from "@/context/UserDetailContext";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        suppressHydrationWarning
        lang="en"
        className={`${roboto.className} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <AiModelProvider>
            <UserDetailProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <SidebarProvider>
                  <AppSidebar />
                  <main className="w-full">
                    <AppHeader />
                    {children}
                    <Toaster />
                  </main>
                </SidebarProvider>
              </ThemeProvider>
            </UserDetailProvider>
          </AiModelProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
